
version: 2

models:
  - name: customers
    description: '{{ doc("coffee_shop") }}'
    columns:
      - name: customer_id
        tests:
           - unique
           - not_null
      - name: name
      - name: email
      - name: n_orders
      - name: first_order_at


  - name: monthly_customers
    description: '{{ doc("coffee_shop") }}'
    columns:
      - name: date_month
      - name: new_customers