version: 2
 
sources:
  - name: coffee_shop
    description: 'Customer data'
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        description: 'Order data'
        columns:
          - name: id
            tests:
              - unique
              - not_null